<wsdl:definitions
     name="dbReferenceRecebeFila"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/RecebeFilaApplication/RecebeFilaProject/dbReferenceRecebeFila"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/RecebeFilaApplication/RecebeFilaProject/dbReferenceRecebeFila"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReferenceRecebeFila"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbReferenceRecebeFila_plt" >
    <plt:role name="dbReferenceRecebeFila_role" >
      <plt:portType name="tns:dbReferenceRecebeFila_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReferenceRecebeFila" schemaLocation="../Schemas/dbReferenceRecebeFila_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DepartamentCollection_msg">
        <wsdl:part name="DepartamentCollection" element="top:DepartamentCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbReferenceRecebeFila_ptt">
        <wsdl:operation name="merge">
            <wsdl:input message="tns:DepartamentCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
